<?php $cartItem = $this->getCart()->getItems(); ?>
<?php //echo '<pre>'; print_r($cartItem); die(); ?>
<h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
<div id="order-items">
	<div class="entry-edit">
		    <div class="grid">
		    	<div class="entry-edit-head">
		   			<h4 class="icon-head head-cart">Cart Data</h4>
			    	<div class="form-buttons"><button type="submit" form="cartform"><span>update Quantity</span></button>
					</div>
			</div>
		        <table cellspacing="0">		           
	                <tr class="headings">
	                	<th class="no-link">#</th>
	                    <th class="no-link">Product Name</th>
	                    <th class="no-link">sku</th>
	                    <th class="no-link">Qty</th>
	                    <th class="no-link">Price</th>
	                    <th class="no-link">Base Price</th>
	                    <th class="no-link last">Action</th>
	                </tr>		           
		            <form id="cartform" method="get" action="<?php echo $this->getUrl('*/adminhtml_order_create/updateCartItem',['id'=>$this->getRequest()->getParam('id')])?>">               
	                	<?php foreach($cartItem as $key => $value):?>
		            		<tr>		       
								<td><?php echo $value->item_id;?></td>
								<td><?php echo $value->name;?></td>
								<td><?php echo $value->sku;?></td>
								<td><input type="text" name="quantity[<?php echo $value->item_id ?>]" value="<?php echo $value->quantity; ?>"></td>
								<td><?php echo $value->price;?></td>
								<td><?php echo $value->base_price;?></td>
								<td>
									<a href="<?php echo $this->getUrl('*/adminhtml_order_create/deleteCartItem',['cartItemId' => $value->item_id ,'id'=> $this->getRequest()->getParam('id')])?>"><button type="button" name="save">delete</button></a>
		                 		</td>
							</tr>
						<?php endforeach;?>
		        </table>		    	
		    </div>
	    </form>
    </div>
</div>