<h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>	
<div class="entry-edit">
        <div class="entry-edit-head">
            <h4>Add Products</h4>
            <div style="float: right;">
                <button type=button name=button style="float: right;"onclick="productGrid();">Add Product</button>    
            </div>
        </div>
</div>
<div id="productGrid">
	<?php echo $this->getChildHtml('productGrid'); ?>
</div>