<?php $order = $this->getOrder(); ?>
<?php $customer = $order->getCustomer(); ?>
<?php $orderItems = $order->getItems(); ?>
<?php $billing = $order->getBillingAddress(); ?>
<?php $shipping = $order->getShippingAddress(); ?>
<div>
	<div id="order-form_account">
		<div class="entry-edit">
	    	<div class="entry-edit-head">
	        	<h4 class="icon-head fieldset-legend head-account">Account Information</h4>
	    	</div>
		    <div id="customer_account_fieds">
		        <div class="fieldset " id="main">
					<div class="hor-scroll">
		                <table cellspacing="0" class="form-list">      				
							<tr>
	    						<td class="label"><label for="name">Name</label></td>
								<td class="value">
	    							<input id="email" name="" value="<?php echo $customer->firstname.' '.$customer->lastname; ?>" type="text" disabled>   
	    						</td>
							</tr>
							<tr>
	    						<td class="label"><label for="email">Email</label></td>
								<td class="value">
	    							<input id="email" name="" value="<?php echo $customer->email; ?>" type="text" disabled>            
	    						</td>
							</tr>
		    			</table>
		        	</div>
		    	</div>
		    </div>    
		</div>
	</div>
</div>  

<div>
  	<div>
		<div id="order-items">
			<div class="entry-edit">
		   		 <div class="grid">
			    	<div class="entry-edit-head">
			   			<h4 class="icon-head head-cart">Cart Data</h4>
					</div>
		       		<table cellspacing="0">		           
	                	<tr class="headings">
		                	<th class="no-link">#</th>
		                    <th class="no-link">Product Name</th>
		                    <th class="no-link">sku</th>
		                    <th class="no-link">Qty</th>
		                    <th class="no-link">Price</th>
		                    <th class="no-link">Base Price</th>
	                	</tr>	
	                	<?php foreach ($orderItems as $key => $value):?>
	                		<tr>
	                			<td><?php echo $value->item_id; ?></td>
	                			<td><?php echo $value->name; ?></td>
	                			<td><?php echo $value->sku; ?></td>
	                			<td><?php echo $value->quantity; ?></td>
	                			<td><?php echo $value->price; ?></td>
	                			<td><?php echo $value->base_price; ?></td>
	                		</tr>
	                	<?php endforeach; ?>	           
		            </table>		    	
		    	</div>
	   		</div>
		</div>  
	</div>
</div>


<div style="display: flex;">  
	<div style="width:60%">
		<div>
			<div class="entry-edit">
    			<div class="entry-edit-head">
        			<h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
    			</div>
    			<fieldset class="np">
    				<div class="order-address" id="order-billing_address_fields">
        				<div class="content">
            				<div class="hor-scroll">
                				<table cellspacing="0" class="form-list">
                        			<tr>
			                            <td class="label">First Name</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $billing->firstname; ?>" type="text">   
			                            </td>
			                        </tr>                               
			                        <tr>
			                            <td class="label">Last Name</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $billing->lastname; ?>" type="text">            
			                            </td>
			                        </tr>
			                        <tr>
			                            <td class="label">Street Address</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $billing->street; ?>" type="text">
			                            </td>
			                        </tr>
			                        <tr>
			                            <td class="label">City</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $billing->city; ?>" type="text"> 
			                            </td>
			                        </tr>
			                        <tr>
			                            <td class="label">Country
			                            </td>
			                            <td class="value">
			                                  <input disabled value="<?php echo $billing->country_id ?>" type="text">   
			                            </td>
			                        </tr>			                
			                        <tr>
			                            <td class="label">State</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $billing->region; ?>" type="text">            
			                            </td>
			                        </tr>
			                        <tr>
			                            <td class="label">ZipCode</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $billing->postcode; ?>" type="text">            
			                            </td>
			                        </tr>
				                </table>
				            </div>
				        </div>
				    </div>
				</fieldset>
			</div>       
		</div>
	</div>
	<div style="margin-left:10px; width:60%">
		<div>
			<div class="entry-edit">
    			<div class="entry-edit-head">
        			<h4 class="icon-head fieldset-legend head-shipping-address">Shipping Address</h4>
     			</div>
    			<fieldset class="np">
    				<div class="order-address" id="order-shipping_address_fields">
        				<div class="content">
            				<div class="hor-scroll">
                				<table cellspacing="0" class="form-list">
									<tr>
			                            <td class="label">First Name</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $shipping->firstname; ?>" type="text">   
			                            </td>
			                        </tr>                               
			                        <tr>
			                            <td class="label">Last Name</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $shipping->lastname; ?>" type="text">            
			                            </td>
			                        </tr>

			                        <tr>
			                            <td class="label">Street Address</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $shipping->street ?>" type="text">
			                            </td>
			                        </tr>
			                        <tr>
			                            <td class="label">City</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $shipping->city; ?>" type="text"> 
			                            </td>
			                        </tr>
			                        <tr>
			                            <td class="label">Country
			                            </td>
			                            <td class="value">
			                                  <input disabled value="<?php echo $shipping->country_id; ?>" type="text">   
			                            </td>
			                        </tr>
			                
			                        <tr>
			                            <td class="label">State</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $shipping->region; ?>" type="text">            
			                            </td>
			                        </tr>
			                        <tr>
			                            <td class="label">ZipCode</td>
			                            <td class="value">
			                                <input disabled value="<?php echo $shipping->postcode; ?>" type="text">            
			                            </td>
			                        </tr>
			            		</tbody>
			    			</table>
			        	</div>
			        </div>
			    </div>
			</fieldset>
		</div>
	</div>
</div>
</div>


<div style="display: flex;">
	<div style="width:60%">
		<div>
		    <div class="entry-edit">
		        <div class="entry-edit-head">
		        	<h4>Billing Method</h4>
		        </div>
		        <fieldset>
		            <?php echo $order->payment_method_code; ?>
		        </fieldset>
		    </div>
		</div>
	</div>
	<div style="margin-left:10px; width:60%">
		<div>
		    <div class="entry-edit">
		        <div class="entry-edit-head">
		            <h4>Shipping Method</h4>
		        </div>
		        <fieldset>
		            <?php echo $order->shipping_method_code.' '.$order->shipping_amount; ?>
		        </fieldset>
		    </div>
		</div>
	</div>
</div>


<div style="display: flex;">
	<div style="width:60%">
		<div>
		    <div class="entry-edit">
		        <div class="entry-edit-head">
		        	<h4>Comment</h4>
		        	<div style="float: right;"></div>
		     	</div>
		     	<span class="field-row">
	           		<label class="normal" for="history_status">Status</label><br>
	            		<select name="history[status]" class="select" id="history_status">
	                        <option value="pending" selected="selected">Pending</option>
	                    </select>
        		</span>
		   		<span class="field-row">
		            <label class="normal" for="history_comment">Comment</label>
		            <textarea name="" rows="3" cols="5" style="height:6em; width:99%;"></textarea>
		        </span>
		    </div>
		</div>
	</div>
	<div style="margin-left:10px; width:60%">
		<div>
		    <div class="entry-edit">
		    	<div class="entry-edit-head">
		        	<h4>Total</h4>
		        </div>
		        <div id="order-totals" class="order-totals">
			        <table cellspacing="0" cellpadding="5">
		                <tr>
		                    <td style="" class="a-right" colspan="1">
		                        Total   
		                    </td>
		                    <td style="" class="a-right">
		                        <span class="price"><?php echo $order->total; ?></span>    
		                    </td>
		                </tr>
		                <tr>
		                    <td style="" class="a-right" colspan="1">
		                        Shipping Charges 
		                    </td>
		                    <td style="" class="a-right">
		                        <span class="price"><?php echo $order->shipping_amount; ?></span>    
		                    </td>
		                </tr>
		                <tr>
		                    <td style="" class="a-right" colspan="1">
		                        <strong>Grand Total</strong>
		                    </td>
		                    <td style="" class="a-right">
		                        <strong><span class="price"><?php echo $order->total+$order->shipping_amount; ?></span></strong>
		                    </td>
		                </tr>
			        </table>
		    	</div>
    		</div>
		</div>
	</div>
</div>


